repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort .
        language: system
        types: [python]
        pass_filenames: false


      - id: black
        name: black
        entry: poetry run black .
        language: system
        types: [python]
        pass_filenames: false

      - id: end-of-file-fixer
        name: fix end of file
        entry: poetry run pre-commit-hooks end-of-file-fixer
        language: system
        types: [text]
        pass_filenames: false

      - id: trailing-whitespace
        name: remove trailing whitespace
        entry: poetry run pre-commit-hooks trailing-whitespace
        language: system
        types: [text]
        pass_filenames: false
