services:
  snowflake_cli:
    image: python:3.11
    container_name: snowflake_cli
    working_dir: /app
    command: >
      bash -c "
        pip install --no-cache-dir snowflake-cli-labs &&
        echo 'Snowflake CLI installed.' &&
        tail -f /dev/null
      "
    volumes:
      - .:/app
    environment:
      SNOWFLAKE_ACCOUNT: ${SNOWFLAKE_ACCOUNT}
      SNOWFLAKE_USER: ${SNOWFLAKE_USER}
      SNOWFLAKE_PASSWORD: ${SNOWFLAKE_PASSWORD}
      SNOWFLAKE_ROLE: ${SNOWFLAKE_ROLE}
      SNOWFLAKE_DATABASE: ${SNOWFLAKE_DATABASE}
      SNOWFLAKE_SCHEMA: ${SNOWFLAKE_SCHEMA}
    tty: true
    stdin_open: true
